package org.egov.mobileapp.models;

import java.math.BigDecimal;
import java.util.Date;

import org.egov.infstr.models.BaseModel;

/**
 * ReceiptHeader generated by hbm2java
 */
public class FieldCollection extends BaseModel {
    /**
     * Serial version uid
     */
    private static final long serialVersionUID = 1L;
    
    
    private BigDecimal collectionType;
    private BigDecimal amount;
    private String manualReceiptNumber;
    private Date manualReceiptDate;
    private Date receiptDate;
	/**
	 * @return the collectionType
	 */
	public BigDecimal getCollectionType() {
		return collectionType;
	}
	/**
	 * @param collectionType the collectionType to set
	 */
	public void setCollectionType(BigDecimal collectionType) {
		this.collectionType = collectionType;
	}
	/**
	 * @return the amount
	 */
	public BigDecimal getAmount() {
		return amount;
	}
	/**
	 * @param amount the amount to set
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	/**
	 * @return the manualReceiptNumber
	 */
	public String getManualReceiptNumber() {
		return manualReceiptNumber;
	}
	/**
	 * @param manualReceiptNumber the manualReceiptNumber to set
	 */
	public void setManualReceiptNumber(String manualReceiptNumber) {
		this.manualReceiptNumber = manualReceiptNumber;
	}
	/**
	 * @return the manualReceiptDate
	 */
	public Date getManualReceiptDate() {
		return manualReceiptDate;
	}
	/**
	 * @param manualReceiptDate the manualReceiptDate to set
	 */
	public void setManualReceiptDate(Date manualReceiptDate) {
		this.manualReceiptDate = manualReceiptDate;
	}
	/**
	 * @return the receiptDate
	 */
	public Date getReceiptDate() {
		return receiptDate;
	}
	/**
	 * @param receiptDate the receiptDate to set
	 */
	public void setReceiptDate(Date receiptDate) {
		this.receiptDate = receiptDate;
	}
    

}
